main(){
  try {
    List a=[6];
    a[6]=30/0;
    try {
      List a = [5];
      a[5] = 30 / 0;
    }
    catch (e) {
      print("Arithmetic exception occurs");
    }
  }catch (e){
    print("error");
  }
}
